services:
  - type: web
    name: safesignal
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TIDB_HOST
        sync: false
      - key: TIDB_PORT
        value: "4000"
      - key: TIDB_DATABASE
        sync: false
      - key: TIDB_USER
        sync: false
      - key: TIDB_PASSWORD
        sync: false
