spring.datasource.url=jdbc:mysql://localhost:3306/safesignal?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Takeshisendo@2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false